# Generated by Django 5.2 on 2025-11-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_currency_sharedaccountmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('investment', 'Investment'), ('loan', 'Loan'), ('saving', 'Saving')], max_length=10),
        ),
    ]
